dist: focal

before_install:
  # Prepare the old build environment
  - sudo apt-get install -y python3-polib python3-pyelftools
  # Bootstrap new build environment
  - ./utils/bootstrap.py
  # Arduino IDE adds a lot of noise caused by network traffic, trying to firewall it off
  - sudo iptables -P INPUT DROP
  - sudo iptables -P FORWARD DROP
  - sudo iptables -P OUTPUT ACCEPT
  - sudo iptables -A INPUT -i lo -j ACCEPT
  - sudo iptables -A OUTPUT -o lo -j ACCEPT
  - sudo iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

jobs:
  include:
    # legacy build.sh environment
    - stage: legacy
      script: ./.github/travis/legacy-build.sh

    # cmake-based build
    - stage: cmake
      script: ./.github/travis/cmake-build.sh

    # cmake tests
    - stage: tests
      script: ./.github/travis/cmake-test.sh

stages:
  - cmake
  - legacy
  - tests
